### ISSUE TITLE
Code 1: xcrun: error

### ISSUE THREAD

**Issue by neilpat05** [giovannicoppola/alfred-powerthesaurus#2]
<img width="775" alt="image" src="https://github.com/giovannicoppola/alfred-powerthesaurus/assets/101647050/66ddbd47-9b39-4a13-ae4e-74d46d0b52d9">

Am I doing something wrong? New to this whole thing, so could very well be making a blooper.

**Comment by giovannicoppola** [comment]
please check this post:
https://www.alfredforum.com/topic/20088-one-workflow-problem-led-to-another-cal/?do=findComment&comment=103767

**Comment by giovannicoppola** [comment]
@neilpat05 is this resolved?

**Comment by pearresearch** [comment]
@giovannicoppola Oh, I forgot to reply. Yes, it is. Thank you for your help!
